import { z } from "zod";

const basePartnerSchema = z.object({
  company_name: z.string().min(2, "Le nom de la société doit contenir au moins 2 caractères"),
  logo_url: z.string().optional(),
  cover_image_url: z.string().optional(),
  description: z.string().min(100, "La description doit contenir au moins 100 caractères"),
  headquarters_address: z.string().min(5, "L'adresse doit contenir au moins 5 caractères"),
  email: z.string().email("Email invalide"),
  phone: z.string().min(8, "Numero de téléphone invalide"),
  whatsapp: z.string().optional(),
  website: z.string().url("URL invalide").optional().or(z.literal("")),
  countries: z.array(z.string()).min(1, "Sélectionnez au moins un pays"),
  cities: z.array(z.string()).min(1, "Sélectionnez au moins une ville"),
  languages: z.array(z.string()).min(1, "Sélectionnez au moins une langue"),
});

export const freightPartnerSchema = basePartnerSchema.extend({
  partner_type: z.literal("freight"),
  shipping_methods: z.array(z.string()).min(1, "Sélectionnez au moins une méthode d'expédition"),
  incoterms: z.array(z.string()).min(1, "Sélectionnez au moins un Incoterm"),
  certifications: z.array(z.string()).optional(),
  avg_delivery_days: z.number().min(1, "Le délai doit être d'au moins 1 jour").optional(),
  min_weight_kg: z.number().min(0, "Le poids minimum doit être positif").optional(),
  max_weight_kg: z.number().min(0, "Le poids maximum doit être positif").optional(),
  max_volume_m3: z.number().min(0, "Le volume maximum doit être positif").optional(),
  cargo_types: z.array(z.string()).optional(),
  special_services: z.array(z.string()).optional(),
  insurance_included: z.boolean().optional(),
  real_time_tracking: z.boolean().optional(),
  customs_clearance: z.boolean().optional(),
  required_documents: z.array(z.string()).min(1, "Sélectionnez au moins un document requis"),
  departure_ports_china: z.array(z.string()).min(1, "Sélectionnez au moins un port de depart"),
  arrival_ports_africa: z.array(z.string()).min(1, "Sélectionnez au moins un port d'arrivee"),
  currency: z.string().min(1, "Sélectionnez une devise"),
  price_range_min: z.number().min(0, "Le prix minimum doit être positif").optional(),
  price_range_max: z.number().min(0, "Le prix maximum doit être positif").optional(),
  pricing_method: z.string().optional(),
  payment_methods: z.array(z.string()).min(1, "Sélectionnez au moins un mode de paiement"),
  payment_terms: z.string().optional(),
  payment_delay_days: z.number().min(0, "Le délai de paiement doit être positif").optional(),
  additional_fees: z.string().optional(),
  warehouse_china: z.boolean().optional(),
  warehouse_china_location: z.string().optional(),
  warehouse_africa: z.boolean().optional(),
  warehouse_africa_location: z.string().optional(),
  own_fleet: z.boolean().optional(),
  fleet_size: z.number().min(0, "La taille de la flotte doit être positive").optional(),
  local_partners: z.string().optional(),
  monthly_capacity: z.number().min(0, "La capacite mensuelle doit être positive").optional(),
  staff_count: z.number().min(1, "Le nombre d'employes doit être d'au moins 1").optional(),
});

export const localLogisticsPartnerSchema = basePartnerSchema.extend({
  partner_type: z.literal("local"),
  service_types: z.array(z.string()).min(1, "Sélectionnez au moins un type de service"),
  coverage_zones: z.array(z.string()).min(1, "Sélectionnez au moins une zone de couverture"),
  same_day_delivery: z.boolean(),
  delivery_time_hours: z.number().min(1, "Le délai de livraison doit être d'au moins 1 heure").optional(),
  express_delivery: z.boolean().optional(),
  express_time_hours: z.number().min(0.5, "Le délai express doit être d'au moins 30 minutes").optional(),
  scheduled_delivery: z.boolean().optional(),
  weekend_delivery: z.boolean().optional(),
  delivery_time_slot: z.string().optional(),
  max_weight_per_parcel_kg: z.number().min(0, "Le poids maximum doit être positif").optional(),
  max_dimensions_cm: z.string().optional(),
  vehicle_types: z.array(z.string()).min(1, "Sélectionnez au moins un type de vehicule"),
  vehicle_fleet_size: z.number().min(1, "Le nombre de vehicules doit être d'au moins 1"),
  delivery_staff_count: z.number().min(1, "Le nombre de livreurs doit être d'au moins 1").optional(),
  storage_available: z.boolean(),
  storage_capacity_sqm: z.number().min(0, "La capacite de stockage doit être positive").optional(),
  warehouse_type: z.string().optional(),
  warehouse_addresses: z.string().optional(),
  security_system: z.array(z.string()).optional(),
  storage_insurance: z.boolean().optional(),
  min_storage_days: z.number().min(0, "La duree minimum doit être positive").optional(),
  max_storage_days: z.number().min(0, "La duree maximum doit être positive").optional(),
  inventory_system: z.boolean().optional(),
  real_time_inventory: z.boolean().optional(),
  currency: z.string().min(1, "Sélectionnez une devise"),
  price_per_delivery: z.number().min(0, "Le prix par livraison doit être positif").optional(),
  min_delivery_price: z.number().min(0, "Le prix minimum doit être positif").optional(),
  price_per_km: z.number().min(0, "Le prix par km doit être positif").optional(),
  price_per_kg: z.number().min(0, "Le prix par kg doit être positif").optional(),
  price_per_sqm_storage: z.number().min(0, "Le prix de stockage doit être positif").optional(),
  handling_fees: z.boolean().optional(),
  handling_fees_amount: z.number().min(0, "Les frais de manutention doivent être positifs").optional(),
  payment_methods: z.array(z.string()).min(1, "Sélectionnez au moins un mode de paiement"),
  payment_terms: z.string().optional(),
  closing_available: z.boolean().optional(),
  closing_zones: z.array(z.string()).optional(),
  closing_with_fitting: z.boolean().optional(),
  returns_accepted: z.boolean().optional(),
  return_conditions: z.string().optional(),
  closing_commission_percent: z.number().min(0).max(100, "La commission doit être entre 0 et 100%").optional(),
});

export type FreightPartnerFormData = z.infer<typeof freightPartnerSchema>;
export type LocalLogisticsPartnerFormData = z.infer<typeof localLogisticsPartnerSchema>;
